### ISSUE TITLE
Crear una estructura básica

### ISSUE THREAD

**Issue by idcmardelplata** [Programacion-collab/Recursos-programacion#1]
Hola, creo que sería bueno crear una estructura básica para poder organizar los recursos que vayamos agregando al README.md ¿te parece la idea?, Así no tenemos todo mezclado y es más fácil buscar algo. @Programacion-collab

**Comment by noisyBrain** [comment]
1. ### Desarrollo Web
    - **Frontend**
        - Roadmap
        - Herramientas online
        - Artículos
        - Cursos
        - Recomendados de Youtube
        - Libros (enlace al terabox)
    - **Backend**
       - Roadmap
        - Herramientas online
        - Artículos
        - Cursos
        - Recomendados de Youtube
        - Libros (enlace al terabox)
2. ### Editores de texto
    - **Vim/Neovim**
      - Cómo empezar
      - Guías en Youtube
      - Learn vim while playing
    - VsCode
      - Extensiones indispensables
      - Artículos
      - Customización
3. ### Git y GitFlow
    - **Git**
      - Cómo empezar
      - Guías en Youtube
    - **GitFlow**
      - Cómo empezar
      - Artículos
      - Buenas prácticas


Se me ocurre, en base a lo que estuvimos charlando, una estructura más o menos como esta. Agregué algunas categorías con tópicos y nombres específicos que redirigirían a cada uno. Creo que se podrían encontrar fácil si están bien especificados dentro de cada catergoría y subcategoría. Qué te parece?

**Comment by idcmardelplata** [comment]
Me parece simplemente genial la estructura, mañana si queres me pongo a armarla en el readme y ya comienzo a subir contenido. Lo que si la parte de libros podríamos poner los nombres pero ningún link para que no nos cierren el repo te parece?, total los links los ponemos en la descripción del grupo directamente. :muscle: :muscle:
