### ISSUE TITLE
Agregar un listado de cursos completos gratuitos en español

### ISSUE THREAD

**Issue by idcmardelplata** [Programacion-collab/Recursos-programacion#2]
Habia pensado en que podriamos buscar y agregar al listado cursos completos sobre programacion en castellano (de distintas areas obviamente), creo que ese seria un muy copado recurso para aquellos que estan queriendo arrancar y no tienen una guia clara a seguir. ¿Que te parece?

**Comment by noisyBrain** [comment]
Excelente idea, Martín! Ni bien encuentre algún recurso copado para agregar, hago un PR.
Justamente ahora, en el curso del programa ONE para el que fui becado, estoy viendo un curso de Git muy interesante, básico, pero interesante. A medida que vaya descubriendo herramientas online que pueden servir, también voy a ir haciendo PR de eso.
Saludos!
